name: CI
 
on: [push]
 
jobs:
  build:
 
    runs-on: ubuntu-latest
     
    steps:
    - uses: actions/checkout@v1
 
    - uses: actions/gcloud/auth@master
      env:
        GCLOUD_AUTH: ${{ secrets.GCLOUD_AUTH }}
 
    - uses: actions/gcloud/cli@master
      with:
        args: "app deploy --quiet --project=testproject-316222"
