name: CI
 
on: [push]
 
jobs:
  build:
 
    runs-on: ubuntu-latest
     
    steps:
    - uses: actions/checkout@v1
    
    - id: deploy
      uses: google-github-actions/deploy-appengine@main
      with:
        project_id: testproject-316222
        credentials: ${{ secrets.GCLOUD_AUTH }}

    # # Example of using the output
    # - id: test
    #   run: curl "${{ steps.deploy.outputs.url }}"
    #   https://github.com/google-github-actions/deploy-appengine for
    #   instructions
